CORE_IP_ADDR:
CORE_USER: guest
CORE_PASSWORD: test
CORE_BROKER_CPORT: 5672
CORE_BROKER_HPORT: 5000
CORE_RESULT_CPORT: 6379
CORE_RESULT_HPORT: 6000
CORE_TMP_MOUNT: mounts/io_tmp/
COMPOSE_PROJECT_NAME: kettle
COMPOSE_IGNORE_ORPHANS: True