REQUIRED_ENV_VARS:
 - COMPOSE_PROJECT_NAME
 - CORE_IP_ADDR
 - CORE_USER
 - CORE_PASSWORD
 - CORE_BROKER_HPORT
 - CORE_RESULT_HPORT
 - CORE_KETTLE_ROOT_DIR
 - CORE_TMP_MOUNT
 - DRIVER_NAME
 - DRIVER_NUM_WORKERS
